server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # SPA fallback
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Proxy para a API (Usando o nome interno do Railway)
    location /auth/ {
        proxy_pass http://monitoring-system:3000/auth/;
        proxy_set_header Host $host;
    }

    location /metrics/ {
        proxy_pass http://monitoring-system:3000/metrics/;
        proxy_set_header Host $host;
    }

    location /hosts {
        proxy_pass http://monitoring-system:3000/hosts;
        proxy_set_header Host $host;
    }

    location /alerts {
        proxy_pass http://monitoring-system:3000/alerts;
        proxy_set_header Host $host;
    }

    location /stats {
        proxy_pass http://monitoring-system:3000/stats;
        proxy_set_header Host $host;
    }

    gzip on;
    gzip_types text/plain text/css application/json application/javascript;
}
