# Imagem base leve do Python
FROM python:3.9-slim

# Diretório de trabalho
WORKDIR /app

# Instala dependências do sistema necessárias para ping
RUN apt-get update && apt-get install -y iputils-ping && rm -rf /var/lib/apt/lists/*

# Instala bibliotecas Python
RUN pip install --no-cache-dir requests psutil

# Copia o script do agent
COPY local_agent.py .

# Variáveis de ambiente (podem ser sobrescritas no docker run)
ENV INGEST_URL=https://monitoring-system-production-1e5a.up.railway.app/metrics
ENV DEVICE_TOKEN=""
ENV INTERVAL=10

# Comando para rodar o agent
CMD ["python", "local_agent.py"]
