apiVersion: apps/v1
kind: DaemonSet          # ← DaemonSet garante 1 agent por node automaticamente
metadata:
  name: agent
  namespace: monitoring
  labels:
    app: agent
spec:
  selector:
    matchLabels:
      app: agent
  template:
    metadata:
      labels:
        app: agent
    spec:
      hostPID: true       # acesso ao PID do host para métricas reais
      containers:
      - name: agent
        image: yourrepo/agent:latest
        env:
        - name: INGEST_URL
          value: "http://ingest-api/metrics"
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName   # hostname = nome do node K8s
        resources:
          requests:
            cpu: "10m"
            memory: "32Mi"
          limits:
            cpu: "100m"
            memory: "64Mi"
